spring:
  profiles:
    active: live
  datasource:
    url: jdbc:h2:file:~/cashback
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

spotify:
  config:
    authUrl: https://accounts.spotify.com/api/token
    clientId: [YOUR_CLIENT_ID]
    clientSecret: [YOUR_CLIENT_SECRET]
    grantType: client_credentials
    searchUrl: https://api.spotify.com/v1/search
    searchType: artist
    artistsUrl: https://api.spotify.com/v1/artists/

albums:
  limit: 2

error:
  message:
    bad_gateway: Erro ao comunicar com o gateway
    internal_server_error: Ocorreu um erro desconhecido. Entre em contato com o administrador do sistema
    not_found: O recurso solicitado não foi encontrado

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - com.github.raphaelbluteau.cashback.exceptions.data.SpotifyException
        - com.github.raphaelbluteau.cashback.exceptions.data.SpotifyAuthException
        - java.io.IOException

  instances:
    spotify:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 100
      retryExceptions:
        - com.github.raphaelbluteau.cashback.exceptions.data.SpotifyException
        - com.github.raphaelbluteau.cashback.exceptions.data.SpotifyAuthException
        - java.io.IOException

  instances:
    spotify:
      baseConfig: default

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 100
  instances:
    spotify:
      maxConcurrentCalls: 10

resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 4
      coreThreadPoolSize: 2
      queueCapacity: 2
  instances:
    spotify:
      baseConfig: default
