spring:
  profiles:
    active: live
  datasource:
    url: jdbc:h2:file:~/cashback
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

spotify:
  config:
    authUrl: https://accounts.spotify.com/api/token
    clientId: [YOUR_CLIENT_ID]
    clientSecret: [YOUR_CLIENT_SECRET]
    grantType: client_credentials
    searchUrl: https://api.spotify.com/v1/search
    searchType: artist
    artistsUrl: https://api.spotify.com/v1/artists/

albums:
  limit: 2

error:
  message:
    bad_gateway: Erro ao comunicar com o gateway
    internal_server_error: Ocorreu um erro desconhecido. Entre em contato com o administrador do sistema
    not_found: O recurso solicitado não foi encontrado

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
